apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: po1
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: po1
  destination:
    namespace: po1
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/stuartbannerman/po1-gateway-infra
      path: envs/dev
      targetRevision: HEAD
    - repoURL: https://github.com/stuartbannerman/po1-service-demo-infra
      path: envs/dev
      targetRevision: HEAD
    - repoURL: https://github.com/stuartbannerman/po1-nextjs-infra
      path: envs/dev
      targetRevision: HEAD
    - repoURL: https://github.com/stuartbannerman/po1-b2c-cms-infra
      path: envs/dev
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    namespace: po1
    name: po1-nextjs
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: Deployment
    namespace: po1
    name: po1-gateway
    jsonPointers:
    - /spec/replicas
