apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: argocd
# nameSuffix: ''

resources:
- ../../../base/apps

components:
- ../../../variants/dev/apps

patchesStrategicMerge: []

# transformers:
#   - |-
#     apiVersion: builtin
#     kind: NamespaceTransformer
#     metadata:
#       name: notImportantHere
#       namespace: argocd
#     unsetOnly: true