apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: po1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: po1
  destination:
    namespace: po1
    server: https://kubernetes.default.svc
  sources:
    - chart: po1-gateway
      repoURL: https://github.com/stuartbannerman/po1-gateway-infra
      targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true