apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: po1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: po1
  destination:
    namespace: po1
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/stuartbannerman/po1-gateway-infra
      path: envs/dev
      targetRevision: HEAD
    - repoURL: https://github.com/stuartbannerman/po1-service-demo-infra
      path: envs/dev
      targetRevision: HEAD
    - repoURL: https://github.com/stuartbannerman/po1-nextjs-infra
      path: envs/dev
      targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: po1-keda-sqs-test
  namespace: po1
spec:
  scaleTargetRef:
    name: dev-po1-nextjs
  minReplicaCount: 1  # We don't want pods if the queue is empty
  maxReplicaCount: 5  # We don't want to have more than 5 replicas
  pollingInterval: 10 # How frequently we should go for metrics (in seconds)
  cooldownPeriod:  60 # How many seconds should we wait for downscale
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: po1-keda-sqs-credentials
    metadata:
      queueURL: https://sqs.eu-west-1.amazonaws.com/236731556556/po1-k8-sqs-test.fifo
      queueLength: "2"
      awsRegion: "eu-west-1"
      identityOwner: operator
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: po1-keda-sqs-credentials
  namespace: po1
spec:
  podIdentity:
    provider: aws-eks
